name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            :pushpin: New push to main branch!
            Commit: ${{ github.event.head_commit.message }}
            Author: ${{ github.event.head_commit.author.username }}
