name: mkdocs workflow

on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
  
    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Login to Container Registory
       uses: docker/login-action@v2
       with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
     - name: Build project
       uses: docker/build-push-action@v4
       with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ vars.REPOSITORY }}:latest
            ghcr.io/${{ vars.REPOSITORY }}:${{ github.run_number }}
